package: info_center
version: '2.3.5'
author: 'KLXM Crossmedia GmbH'
supportpage: https://github.com/klxm/info_center

load: late

requires:
    redaxo: '^5.18.0'
    php:
        version: '>=8.1'
    packages:
        structure: '^2.0.0'

page:
    title: 'translate:info_center_title'
    perm: info_center[]
    pjax: false
    icon: rex-icon fa-info-circle
    hidden: true
    subpages:
        config: 
            title: 'translate:info_center_settings'
            perm: info_center[config]
        widget_builder: 
            title: 'translate:info_center_widget_builder'
            perm: info_center[admin]
            pjax: false

default_config:
    darkmode: auto
    position: right
    widgets:
        url:
            enabled: true
            prio: -1
        timetracker:
            enabled: true
            prio: 0
        article:
            enabled: true 
            prio: 1
        upkeep:
            enabled: true
            prio: 2
        messaging:
            enabled: true
            prio: 3
        stats:
            enabled: true
            prio: 5
        system:
            enabled: true
            prio: 10

default_permissions:
    info_center: 'Info Center'
    info_center[config]: 'Info Center Settings'
    info_center[recent_articles]: 'Zuletzt bearbeitete Artikel anzeigen'
    info_center[all_articles]: 'Alle Artikel-Änderungen sehen (nicht nur eigene)'

conflicts:
    packages:
        minibar: '*'
