package: info_center
version: '1.0.0-dev'
author: 'KLXM Crossmedia GmbH'
supportpage: https://github.com/klxm/info_center

load: late

requires:
    redaxo: '^5.18.0'
    php:
        version: '>=8.1'
    packages:
        structure: '^2.0.0'
        quick_navigation: '*'

default_config:
    darkmode: auto
    position: right
    widgets:
        article:
            enabled: true 
            prio: 1
        system:
            enabled: true
            prio: 10
        stats:
            enabled: true
            prio: 5
        upkeep:
            enabled: true
            prio: 30

conflicts:
    packages:
        minibar: '*'
